version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_container
    hostname: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PASSWORD: "${DB_PASSWORD}"
      MSSQL_USER: "${DB_USER}"
      MSSQL_DB_NAME: "${DB_NAME}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - mssqlnet

  initdb:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver_initdb
    depends_on:
      - sqlserver
    entrypoint: >
      /bin/bash -c "
        echo 'Aguardando o SQL Server iniciar...';
        until /opt/mssql-tools/bin/sqlcmd -S sqlserver,1433 -U '${DB_USER}' -P '${DB_PASSWORD}' -Q 'SELECT 1' > /dev/null 2>&1;
        do
          echo 'Esperando SQL Server...'; sleep 2;
        done;
        echo 'Criando o banco curso_clean_arch...';
        /opt/mssql-tools/bin/sqlcmd -S sqlserver,1433 -U sa -P '${DB_PASSWORD}' -i /init.sql;
        echo 'Banco criado com sucesso!';
      "
    volumes:
      - ./init.sql:/init.sql
    networks:
      - mssqlnet

volumes:
  mssql_data:

networks:
  mssqlnet:
    driver: bridge
